import { Fraunces, Inter } from '@next/font/google';
import Head from 'next/head';
import { PropsWithChildren } from 'react';

import { Navbar } from './Navbar';

const inter = Inter({
  weight: ['300', '400'],
  subsets: ['latin'],
  variable: '--font-inter',
});

const fraunces = Fraunces({
  subsets: ['latin'],
  axes: ['opsz', 'SOFT'],
  variable: '--font-fraunces',
});

export function Layout({ children }: PropsWithChildren) {
  return (
    <>
      <Head>
        <title>Chester How</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`${inter.variable} ${fraunces.variable} mx-auto w-full max-w-screen-sm px-2 pb-1 font-sans md:max-w-screen-lg xl:max-w-screen-2xl`}
      >
        <Navbar />
        <div className="grid grid-flow-row-dense grid-cols-2 md:grid-cols-3 xl:grid-cols-4">
          {children}
        </div>
      </main>
    </>
  );
}
