import { Fraunces, Inter } from '@next/font/google';
import Head from 'next/head';

const inter = Inter({
  weight: ['300', '400'],
  subsets: ['latin'],
  variable: '--font-inter',
});

const fraunces = Fraunces({
  subsets: ['latin'],
  axes: ['opsz', 'SOFT'],
  variable: '--font-fraunces',
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.variable} ${fraunces.variable} font-sans`}>
        <h1 className="font-serif-variation font-serif text-4xl font-light">
          Hello world
        </h1>
      </main>
    </>
  );
}
