import { Fraunces, Inter } from '@next/font/google';
import { InferGetStaticPropsType } from 'next';
import Head from 'next/head';

import { Card } from '@/components/Card';
import { IntroCard } from '@/components/IntroCard';
import { supabase } from '@/lib/supabaseClient';

const inter = Inter({
  weight: ['300', '400'],
  subsets: ['latin'],
  variable: '--font-inter',
});

const fraunces = Fraunces({
  subsets: ['latin'],
  axes: ['opsz', 'SOFT'],
  variable: '--font-fraunces',
});

export default function Home(
  props: InferGetStaticPropsType<typeof getStaticProps>
) {
  return (
    <>
      <Head>
        <title>Chester How</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`${inter.variable} ${fraunces.variable} mx-auto w-full max-w-screen-2xl p-3 font-sans`}
      >
        <div className="grid grid-flow-row-dense grid-cols-3 lg:grid-cols-4">
          <IntroCard />
          {props.featured?.map(({ card }) =>
            card && !Array.isArray(card) ? (
              <Card key={card.id} {...card} />
            ) : null
          )}
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const { data: featured } = await supabase
    .from('featured')
    .select('ordering, card:cards(*)')
    .order('ordering');

  return {
    props: {
      featured,
    },
  };
}
